version: "3.8"
services:
  web:
    image: php:8.1-apache
    ports:
      - "80:80"
    volumes:
      - ./public-html:/var/www/html
      - uploads:/var/www/uploads   # 永続化されたボリュームをマウント
    depends_on:
      - mysql

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db_data:/var/lib/mysql

volumes:
  uploads:  # 永続化されたボリュームの定義
  db_data:
